on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-cf:
    environment:
      name: cloudflare-pages
      url: https://local-fonts.ssssota.dev/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm
        run: pnpm wasm
      - name: Build svelte
        run: pnpm build
        env:
          PUBLIC_GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      - run: npx wrangler pages publish build --project-name local-fonts
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
